const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const {AsyncLocalStorage}=require('node:async_hooks');
test('entry reports route per league + general; exact cache expires without sliding; delivery retries',async()=>{
 const context=new AsyncLocalStorage(),configs={ash:{validationChannelId:'a'},rtg:{validationChannelId:'r'},test:{validationChannelId:'t'}},sessions={},sent=[];
 let fail=false;
 const database={withGuild:(guild,fn)=>context.run(guild,fn),readConfig:()=>structuredClone(configs[context.getStore()]||{}),saveConfig:value=>{configs[context.getStore()]=structuredClone(value);}};
 const sandbox={module:{exports:{}},console,require:name=>{
  if(['crypto','discord.js'].includes(name))return require(name);
  if(name==='./database')return database;
  if(name==='./tournamentScope')return {TEST_GUILD:'test',allowedGuild:g=>['ash','rtg','test'].includes(g)};
  if(name==='./hostValidationContext')return require('../utils/hostValidationContext');
  if(name==='./hostNetworkMatches')return require('../utils/hostNetworkMatches');
  if(name==='./haxoleSupabase')return {upsertPlayerIdentity:async()=>({player:{id:'profile'}})};
  if(name==='./officials')return {updatePendingSession:(id,p)=>Object.assign(sessions[id],p),listPendingSessions:()=>Object.values(sessions),readStore:()=>({pendingSessions:sessions})};
  throw Error(name);
 }};
 vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../utils/antiDu.js'),'utf8'),sandbox);const api=sandbox.module.exports;
 const client={users:{fetch:async()=>({tag:'Discord user'})},channels:{fetch:async id=>({guildId:({a:'ash',r:'rtg',t:'test'})[id],isTextBased:()=>true,send:async payload=>{if(fail&&id==='a'){fail=false;throw Error('temporary');}sent.push({id,payload});}})}};
 const base={guildId:'ash',matchedUserId:'user',matchedBy:'auth',playerName:'belga',auth:'auth',conn:'conn',ip:'ip',room:'Sala',status:'confirmed',reportingV2:true,hostContext:{reportedIp:'192.0.2.42',version:'0.1.1'}};
 const manual=Date.now()-2*60*60*1000;
 sessions.first={...base,id:'first',confirmedAt:new Date(manual).toISOString()};
 fail=true;await assert.rejects(api.recordValidation(client,sessions.first),/temporary/);
 assert.equal(configs.ash.antiDuHistory.length,1);await api.retryReports(client);
 assert.deepEqual(sent.map(r=>r.id),['a','t']);await api.recordValidation(client,sessions.first);assert.equal(sent.length,2,'no duplicated report for retry');
 const next={...base,id:'second',status:'pending',confirmedAt:null};
 assert(api.autoValidation(next));
 for(const field of ['auth','conn','ip','playerName','matchedUserId'])assert.equal(api.autoValidation({...next,[field]:'different'}),null,field);
 assert.equal(api.autoValidation({...next,ip:null}),null,'missing IP is not exact proof');assert.equal(api.autoValidation({...next,matchedBy:'ip'}),null);
 assert.equal(api.autoValidation(next,manual+3*60*60*1000),null,'strictly under three hours');
 sessions.second={...next,status:'confirmed',automatic:true,confirmedAt:new Date().toISOString(),manualConfirmedAt:new Date(manual).toISOString()};
 await api.recordValidation(client,sessions.second);assert.equal(sent.length,4,'new automatic entry also reports');
 assert.equal(api.autoValidation({...next,id:'third'},manual+3*60*60*1000),null,'automatic entry never extends original deadline');
 assert.equal(api.autoValidation({...next,guildId:'rtg'}),null,'league cache isolated');
 sessions.road={...base,id:'road',guildId:'rtg',confirmedAt:new Date().toISOString()};await api.recordValidation(client,sessions.road);assert.deepEqual(sent.slice(-2).map(r=>r.id),['r','t']);
 assert(!JSON.stringify(sent).includes('"auth":"auth"'),'raw connection values never included in reports');
 assert(!JSON.stringify(sent).includes('192.0.2.42'),'host IP is hidden unless channel privacy is confirmed');
 assert(!JSON.stringify(sent).includes('Contexto del host'),'host metadata is not part of Anti-DU');
 assert(!JSON.stringify(sent).includes('Coincidencias del hoster'),'hoster matches stay in the separate creation report');
});
